tasks:
 - command: "clear && echo Installing Tabris, please stand by... && npm install && npm install git://github.com:eclipsesource/tabris-js-cli.git#gitpod-experiments --no-save && npm run start:gitpod"
ports:
 - port: 8080
   onOpen: open-preview
