language: android

jdk:
  - oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-27

env:
  global:
  - BUILD_NUMBER=4

before_install:
  - nvm install 8.12
  - npm install -g npm@^6.4.1
  - npm install -g tabris-cli@3.0.0-beta1
  - yes | sdkmanager "platforms;android-27"

install:
  - npm install

script:
  - gradle -v
  - tabris build android
