language: android

jdk:
  - oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-27

env:
  global:
  - BUILD_NUMBER=4

before_install:
  - nvm install 12
  - npm install -g tabris-cli@latest
  - yes | sdkmanager "platforms;android-28"

install:
  - npm install

script:
  - gradle -v
  - tabris build android
